name: tokyu_envy_report
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  rxdart: ^0.27.7
  mutex: ^3.1.0
  logging: ^1.2.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  flutter_native_splash: ^2.3.9
  intl: ^0.18.1
  firebase_core: ^2.24.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true